name: Deployment pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Install Playwright browsers
        run: npx playwright install
      - name: E2E Test
        run: npm run test:e2e
      - name: Build failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          text: Build failed
          severity: error
          details: commit https://github.com/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.event.commit.author.name }} broke the build :(
          description: ''
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Check commit message
        id: check_message
        run: echo "::set-output name=skip::$(if echo '${{ github.event.head_commit.message }}' | grep -q '#skip'; then echo 'true'; else echo 'false'; fi)"
      - name: Trigger deployment
        id: deploy
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.check_message.outputs.skip == 'false'
      - name: Deployed
        uses: rjstone/discord-webhook-notify@v1
        if: steps.deploy.outcome == 'success'
        with:
          text: A new version of Pokedex deployed
          severity: info
          details: A new version of Pokedex deployed to https://full-stack-open-pokedex-m4ec.onrender.com by ${{ github.event.commit.author.name }}
          description: ''
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Check commit message
      id: check_message
      run: echo "::set-output name=skip::$(if echo '${{ github.event.head_commit.message }}' | grep -q '#skip'; then echo 'true'; else echo 'false'; fi)"
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.check_message.outputs.skip == 'false'